import { Injectable, linkedSignal, signal } from '@angular/core';

export interface CreateBuildRequestBody {
  id: string;
  title: string;
  description: string;
  thumbnail?: string;
}

export interface BuildCardItem {
  title: string;
  thumbnail: string;
}

@Injectable({
  providedIn: 'root',
})
export class BuildsService {
  builds = signal([
    {
      id: '1',
      title: 'build1',
      description: 'this is build1',
      // TODO: Images will be generated by OpenAI API & DALL-E 
      thumbnail: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
    },
    {
      id: '2',
      title: 'build2',
      description: 'this is build1',
    },
    {
      id: '3',
      title: 'build3',
      description: 'this is build1',
      thumbnail: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
    },
  ]);

  buildCardItem = linkedSignal({
    source: this.builds,
    computation: (newBuilds) =>
      newBuilds.map((build) => ({
        title: build.title,
        thumbnail:
          build.thumbnail ||
          'https://material.angular.io/assets/img/examples/shiba2.jpg',
      })),
  });

  createBuild(build: CreateBuildRequestBody) {
    this.builds.set([...this.builds(), build]);
  }

  getBuild(buildId: string) {
    return this.builds().find((build) => build.id === buildId);
  }
}
